module.exports = {
	extends: ['stylelint-config-standard-scss'],
	rules: {
		'font-family-no-missing-generic-family-keyword': null,
		'no-descending-specificity': null,
		'block-no-empty': null,
		'no-duplicate-selectors': null,
		'font-family-no-duplicate-names': null,
		'selector-class-pattern': null,
		'max-nesting-depth': 6,
		'function-url-quotes': null,
		'selector-attribute-quotes': null,
		'rule-empty-line-before': null,
		'declaration-property-unit-allowed-list': {
			'line-height': ['px', 'em', 'rem'],
		},
		'scss/no-global-function-names': null,
		'font-family-name-quotes': null,
		'no-invalid-double-slash-comments': null,
		'custom-property-pattern': null,
		'scss/at-mixin-argumentless-call-parentheses': null,
		'selector-pseudo-element-colon-notation': null,
		'color-function-notation': null,
		'custom-property-empty-line-before': null,
		'scss/double-slash-comment-empty-line-before': null,
		'scss/at-rule-conditional-no-parentheses': null,
		'alpha-value-notation': null,
	},
};
