name: PHPCS

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Enable phpcodesniffer installer
      run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phpcs
      run: composer run-script lint:wpcs
